import {Product} from '../models/product';

export const PRODUCTS: Product[] = [
{
    "productagerating": "13+",
    "productdescription": "Graduation time is finally here, but the girls of the Sakuragaoka Girl's High Light Music Club aren't going to let the end of high school be the end of all they've built together. First though, they have to keep a promise to take a trip together, and like everything else they do, they're not doing it halfway. So it's time to hop on the bus - the double-decker bus that is - and go around the world as the band heads for the birthplace of the British Invasion: the United Kingdom!\n'On the way they're going to have to solve that one last big puzzle that's been vexing them: what to get for their underclassman rhythm guitarist Azusa, who will be taking over the club once they don their caps and gowns and leave Sakuragaoka for the last time. Get ready for a Magical Musical Tour as the whole gang takes in the sights and sounds of London and prepares for one last amazing encore!\n",
        "categoryid": 6,
    "productlength": 110,
        "mediumid": 1,
    "productcode": "KONMOV",
    "productid": 1002,
        "publisherid": 66,
    "ratingid": 5,
    "producttitle": "K-ON: The Movie",
    "unitprice": 39.9797,
    "productyearcreated": 2013,
    "yourprice": 23.9898
},
    {
        "productagerating": "14+",
        "productdescription": "Raised by a mysterious sorcerer after the horrific death of his parents, Shiro Emiya has only just begun to help others using the small tidbits of magic that he's learned. However, when he's suddenly caught in a battle between two more powerful Magus, Shiro finds himself performing a spell above his expected ability, summoning the beautiful spirit warrior Saber to protect him! But safety is only momentary as Shiro and Saber now find themselves thrust into in a secret world of dark magic and deadly challenges: a no-holds barred duel to the death known as the Holy Grail War!\n'At stake is a prize of unimaginable power, but can the inexperienced Shiro and Saber survive long enough to even enter the contest? First they'll have to withstand waves of treachery and assassination, even as Shiro scrambles to learn everything he'll need to know to stay alive as seven teams of Magus and Spirit Servants face off in mortal combat!",
            "categoryid": 1,
        "productlength": 300,
            "mediumid": 1,
        "productcode": "FATESTAY",
        "productid": 1003,
            "publisherid": 66,
        "ratingid": 3,
        "producttitle": "Fate/Stay Night: Unlimited Blade Works",
        "unitprice": 69.9804,
        "productyearcreated": 2013,
        "yourprice": 52.4902
    },
    {
        "productagerating": "14+",
        "productdescription": "Find out what happens when Yuji accidentally triggers a found Treasure Tool while it's pointed at Shana! Then, Yuji teams up with Wilhelmina to stalk their fiery friend - whose secrecy has become unsettling. Finally, in a two-part special, Shana tracks a Denizen's trail by sorting through a Torch's memories for clues. Her sleuth skills reveal a teenage girl's heartwarming last days and a predator with a serious identity crisis!  Contans OVA episodes 1-4: Reshuffle; Domicile; Overture, Part 1; Overture, Part 2; Special Features: Shakugan no Shana-tan G, Shakugan no Shana-tan Dos, Shakugan no Shana-tan Tri-, Shakugan no Shana-tan Frontier, Textless Songs, Trailers.",
            "categoryid": 1,
        "productlength": 110,
            "mediumid": 6,
        "productcode": "SHANA",
        "productid": 1004,
            "publisherid": 18,
        "ratingid": 3,
        "producttitle": "Shakugan no Shana S (OVA)",
        "unitprice": 34.9797,
        "productyearcreated": 2013,
        "yourprice": 20.9898
    },
    {
        "productagerating": "17+",
        "productdescription": "Horrifying beasts with a hunger for human flesh prey on the citizens of a quiet town. In moonlit twilight, Saya slays the monsters and returns home drenched in blood. As the attacks increase in frequency and intensity, her enemies relay cryptic messages about a broken contract. Limbs are torn from flesh and skulls are crushed and devoured while the huntress struggles with paralyzing visions and gaping holes in her memory. When the humans Saya promised to protect reveal the sickening truth about her role in the violence, she learns her mission isn't as clear cut as she thought - and her most sadistic foe of all is so close she can taste it.",
            "categoryid": 11,
        "productlength": 300,
            "mediumid": 6,
        "productcode": "BLOODC",
        "productid": 1005,
            "publisherid": 18,
        "ratingid": 3,
        "producttitle": "Blood C Complete Series",
        "unitprice": 64.9804,
        "productyearcreated": 2013,
        "yourprice": 48.7402
    },
    {
        "productagerating": "14+",
        "productdescription": "There is a train station on the other side of death, yet not all who arrive on the platform will be judged ready for passage onwards. For one unready soul, there will be both a test and a second chance. Rather than be reborn, this soul will awake in the body of 14-year-old suicide Makoto Kobayashi, where it must not only find a way to fit into Makoto's existence, but also unravel two mysteries. What is the secret of the great sin it committed in its own previous life, and what were the reasons that led to Makoto's suicide?  While some may believe the truth to be as plain to see as black and white, \"Makoto\" soon finds that the real world is overlaid with so many shades of grey and rainbows of colors that even the most obvious of \"facts\" are not what they seem. With the soul's time in Makoto's body quickly running out, the answers to all life's mysteries await discovery.",
            "categoryid": 7,
        "productlength": 126,
            "mediumid": 1,
        "productcode": "COLORFUL",
        "productid": 1006,
            "publisherid": 66,
        "ratingid": 3,
        "producttitle": "COLORFUL",
        "unitprice": 39.9797,
        "productyearcreated": 2013,
        "yourprice": 23.9898
    },
    {
        "productagerating": "14+",
        "productdescription": "Natsuru used to dream of being a lady killer. Instead, he got turned into a Kempfer - a lady who's supposed to fight and kill other girls in mortal combat! Now he's stuck splitting his/her days between being a typically average Japanese boy and a very untypical Japanese girl. To make matters even more complex, Natsuru's allowed him/herself to be convinced to move in with three other gorgeous Kampfers, who are definitely all woman all of the time, for their \"mutual defense.\"  Of course, the fact that more than one of them may have less than honorable designs upon one or the other of his/her two alternate sexualities couldn't possibly be a problem, could it? Of course it could, and things really get hopping when Natsuru has to take a job at the Bunnygirl Cafe and ends up in the hot box!",
            "categoryid": 6,
        "productlength": 50,
            "mediumid": 3,
        "productcode": "KAMPFER",
        "productid": 1007,
            "publisherid": 66,
        "ratingid": 4,
        "producttitle": "KAMPFER OVA",
        "unitprice": 19.98,
        "productyearcreated": 2013,
        "yourprice": 14.99
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Disney's megabudget foray into a new CGI franchise of epic sci-fi mythology arrives with a massive marketing push and an interesting pulp pedigree that will probably inspire as many fans as it will naysayers. This impressively crafted piece of escapist fantasy is based on a character and series of books by Edgar Rice Burroughs that is runner-up to his primary creation, Tarzan, and the 20-plus volumes he wrote about that iconic ape-raised jungle adventurer. Burroughs churned out books in both series concurrently for roughly his entire adult life in the first half of the 20th century. John Carter is a former Confederate Civil War captain and fortune-hunting ne'er-do-well who through a weird incident of astral projection is plopped down on the red planet, where he becomes a passionate warrior against beasts and humanoids for the security of a home world known to its inhabitants as Barsoom. John Carter presents this origin setup in a clever prologue that finds the cranky Carter on the run from frontier military authorities as well as a band of marauding Indians. Carter is played by Friday Night Lights star Taylor Kitsch with great bravado. His character undergoes radical change when confronted with something he can finally care about. It doesn't hurt that an exotic princess of Mars is part of the prize package that comes from his battle against evil and ultimately doing the right thing. John Carter is a visual feast (especially in well-conceived 3-D) with an array of digital and motion-capture techniques that create an eye-popping world of strange creatures, astounding architectural vistas, aerial panoramas, and luminous landscapes. All the extraordinary detail is not surprising considering that Pixar superstar Andrew Stanton is at the helm (he also directed Finding Nemo and WALL-E). There's a lot going on in the script, and it sometimes feels as though too much work was done in the editing suite to streamline a story that is often overly complicated. Barsoom is ruled by three species, all with their own political and social agendas. There are the humans whose city-state cultures are threatened by civil war and the aggression of Tharks, a race of giant green-skinned, four-armed warriors with horrific tusks and a deeply bellicose intellect. Separate from both are the mythic Therns, a cultlike sect of über-beings who seek to manipulate all of Barsoom into their own submission. Added to the mix are a variety of outrageous animal creatures both vicious and sublime that make for an extremely motley ensemble of beasties. The huge cast of characters, species, and names becomes a bit confusing to keep straight in all the rapid-fire exposition. Fortunately the movie doesn't ever stop long enough to allow much time for thinking; there's something new and exciting to look at in virtually every scene. Because of some fantastical leaps of physics and gravity, Carter's Martian body possesses super strength and the ability to make single bounds over huge distances. His powers not only make him a godlike presence to the natives of Barsoom, they also provide for some dizzying feats of movie magic. The most bravura element of the conceptual design is a fleet of massive solar-powered flying machines that recall something out of H.G. Wells or a steampunk fantasy. These colorful, insectlike machines soar and float in the gold-hued Martian atmosphere with thrilling precision. Even though the multitude of beings, names, and alliances may sometimes elicit a glassy-eyed response, there's plenty of attention-grabbing exactitude to behold in John Carter. There's also a good chance that the fans will make it worth Disney's while to shell out another hundred million to keep the saga going.",
            "categoryid": 5,
        "productlength": 132,
            "mediumid": 1,
        "productcode": "JCARTER",
        "productid": 1008,
            "publisherid": 62,
        "ratingid": 5,
        "producttitle": "JOHN CARTER",
        "unitprice": 26.5,
        "productyearcreated": 2012,
        "yourprice": 19.0798
    },
    {
        "productagerating": "PG-13",
        "productdescription": "The battle for Earth begins at sea in this epic action-adventure starring Liam Neeson, Taylor Kitsch, Rihanna, Alexander Skarsg†rd and Brooklyn Decker. An international naval coalition becomes the world's last hope for survival as they engage a hostile alien force of unimaginable strength. Ripping across sea, sky and land, Battleship is \"a big bold blast\" (MSN Movies), packed with spectacular visual effects and explosive action. ",
            "categoryid": 5,
        "productlength": 132,
            "mediumid": 1,
        "productcode": "BATTLESHIP",
        "productid": 1009,
            "publisherid": 56,
        "ratingid": 5,
        "producttitle": "BATTLESHIP",
        "unitprice": 29.98,
        "productyearcreated": 2012,
        "yourprice": 14.99
    },
    {
        "productagerating": "PG-13",
        "productdescription": "It has been eight years since Batman vanished into the night, turning, in that instant, from hero to fugitive. Assuming the blame for the death of D.A. Harvey Dent, the Dark Knight sacrificed everything for what he and Commissioner Gordon both hoped was the greater good. For a time the lie worked, as criminal activity in Gotham City was crushed under the weight of the anti-crime Dent Act. But everything will change with the arrival of a cunning cat burglar with a mysterious agenda. Far more dangerous, however, is the emergence of Bane, a masked terrorist whose ruthless plans for Gotham drive Bruce out of his self-imposed exile. But even if he dons the cape and cowl again, Batman may be no match for Bane.",
            "categoryid": 19,
        "productlength": 165,
            "mediumid": 1,
        "productcode": "DARKKNT3",
        "productid": 1010,
            "publisherid": 63,
        "ratingid": 5,
        "producttitle": "The Dark Knight Rises",
        "unitprice": 35.9902,
        "productyearcreated": 2012,
        "yourprice": 24.98
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Rock of Ages tells the story of small town girl Sherrie and city boy Drew, who meet on the Sunset Strip while pursuing their Hollywood dreams. Their rock 'n' roll romance is told through the heart-pounding hits of Def Leppard, Joan Jett, Journey, Foreigner, Bon Jovi, Night Ranger, REO Speedwagon, Pat Benatar, Twisted Sister, Poison, Whitesnake, and more. ",
            "categoryid": 13,
        "productlength": 123,
            "mediumid": 1,
        "productcode": "ROCKOFAGES",
        "productid": 1011,
            "publisherid": 63,
        "ratingid": 4,
        "producttitle": "Rock of Ages",
        "unitprice": 35.9902,
        "productyearcreated": 2012,
        "yourprice": 24.5
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Every year in the ruins of what was once North America, the Capitol of the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games. A twisted punishment for a past uprising and an ongoing government intimidation tactic, the Hunger Games are a nationally televised event in which Tributes must fight with one another until one survivor remains. Sixteen-year-old Katniss Everdeen volunteers in her younger sister’s place to enter the games, and is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy when she’s pitted against highly-trained Tributes who have prepared for these Games their entire lives. If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love.",
            "categoryid": 4,
        "productlength": 142,
            "mediumid": 1,
        "productcode": "HUNGERGMS1",
        "productid": 1012,
            "publisherid": 27,
        "ratingid": 4,
        "producttitle": "The Hunger Games",
        "unitprice": 19.98,
        "productyearcreated": 2012,
        "yourprice": 14.99
    },
    {
        "productagerating": "14+",
        "productdescription": "Kimimaro is a hard-working college student, raised by his grandmother after his mother died and his father went mysteriously missing. Working at a mini-mart to eke out a meager existence while completing his studies, one night he is approached by a strange, clown-like man. This man has an offer: receive a near-endless supply of money through loans leveraged against one's future.  Part of the bargain includes joining other \"Entrepreneurs\" and battling with animal-like \"Assets\" to gain money directly tied to their lives. Intrigued, Kimimaro finds himself fighting alongside his Asset, Mshyu, and inadvertently discovers the twisted ties that secretly hold the World's economy together as well as his own family's past.",
            "categoryid": 16,
        "productlength": 275,
            "mediumid": 6,
        "productcode": "CCONTROL",
        "productid": 1013,
            "publisherid": 18,
        "ratingid": 4,
        "producttitle": "C-Control - Money of Soul and Possibility",
        "unitprice": 69.9804,
        "productyearcreated": 2012,
        "yourprice": 41.9902
    },
    {
        "productagerating": "14+",
        "productdescription": "Keima Katsuragi can score with any girl he wants... provided she's not real. A legendary master of Japanese dating sims and often referred to by other players as the God of Conquests, Keima is a classic nerd in real life and isn't even all that interested in girls with more than two dimensions in the first place! Unfortunately for Keima, his personal preferences cease to be of any importance when he accepts a challenge to what he thinks is an internet game, only to discover the he's actually made a deal with a demon!\n'And not just any demon: this is Elsie, a not particularly competent, young female demon who's been charged with recapturing runaway spirits that prefer to hide in girls hearts, where they can only be driven out by the girls falling in love. Now Elsie's got Keima by a collar and he's got to get the girls or die trying!",
            "categoryid": 14,
        "productlength": 100,
            "mediumid": 3,
        "productcode": "ONLYKNOW1",
        "productid": 1014,
            "publisherid": 66,
        "ratingid": 3,
        "producttitle": "World God Only Knows DVD 1",
        "unitprice": 29.98,
        "productyearcreated": 2012,
        "yourprice": 26.93
    },
    {
        "productagerating": "16+",
        "productdescription": " Distraught over his feelings for Mizuho, Kei has slipped into another standstill. In the depths of his mind, Kei meets a phantom from his past with whom he discusses the joys and sorrows of life. Back aboard her spaceship, Mizuho must decide whether or not to break Galaxy Federation rules in order to revive Kei or risk losing him forever! The choice is made. How can Kei move forward with his normal high school life when he's missing a piece of his heart? ",
            "categoryid": 14,
        "productlength": 100,
            "mediumid": 3,
        "productcode": "ONEGAI4",
        "productid": 1558,
            "publisherid": 7,
        "ratingid": 5,
        "producttitle": "Onegai Teacher  DVD 4: Hello Again",
        "unitprice": 29.98,
        "productyearcreated": 2002,
        "yourprice": 9.99002
    },
    {
        "productagerating": "13+",
        "productdescription": "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil. And when he vows to defend Rukia from the ruthless justice of the Soul Society, he and his friends must cross over and do battle in the spirit world... Contains episodes 1-4.",
            "categoryid": 1,
        "productlength": 100,
            "mediumid": 3,
        "productcode": "BLEACH1",
        "productid": 1016,
            "publisherid": 61,
        "ratingid": 3,
        "producttitle": "BLEACH DVD 1",
        "unitprice": 24.98,
        "productyearcreated": 2012,
        "yourprice": 5
    },
    {
        "productagerating": "R",
        "productdescription": "United States Special agent Leon S. Kennedy sneaks into a small Eastern European country to verify rumors that Bio Organic Weapons (B.O.W.s) are being used in war. Right after his infiltration, the US government orders him to leave immediately. Determined to uncover the truth, Leon ignores the order and enters the battlefield to end the chain of tragedies caused by the B.O.W.s. ",
            "categoryid": 1,
        "productlength": 100,
            "mediumid": 3,
        "productcode": "RESIDENTN2",
        "productid": 1017,
            "publisherid": 45,
        "ratingid": 3,
        "producttitle": "Resident Evil: Damnation",
        "unitprice": 26.9898,
        "productyearcreated": 2012,
        "yourprice": 17.9898
    },
    {
        "productagerating": "17+",
        "productdescription": "The sequel to ef ~ A Tale of Memories! \n'Shuichi Kuze's been spending time with Mizuki Hayama, and as they've been getting to know each other, they've been growing closer. Sadly, Kuze discovers that he's contracted a fatal illness and decides to break all romantic ties for the little time left to him. Before he can break things off, however, Mizuki tells him that she loves him. Will her declaration change Kuze's mind?\n'In another city, in the not-so-distant past, Yuu Himura meets a girl who seems to know him, but he doesn't know her. Soon enough, he remembers Yuko Amamiya, a girl he met long ago, and begins to rediscover the depth of their feelings for each other. Will Yuko's love reach across time to find her true love once and for all? Kuze and Mizuki, Yu and Yuko... Intertwining fate, tragic, bittersweet and beautiful.\n'Contains episodes 1-12.",
            "categoryid": 7,
        "productlength": 300,
            "mediumid": 1,
        "productcode": "EFTALE",
        "productid": 1019,
            "publisherid": 66,
        "ratingid": 2,
        "producttitle": "EF - A Tale of Melodies",
        "unitprice": 69.9804,
        "productyearcreated": 2012,
        "yourprice": 41.9902
    },
    {
        "productagerating": "14+",
        "productdescription": "Odd Jobs Gin has taken on a lot of odd work in the past, and when you're a Jack of All Trades agency based in a feudal Japan that's been conquered and colonized by aliens, the term \"Odd Jobs\" means REALLY ODD jobs. But when some more than slightly suspicious secrets from the shadows of Gintoki Sakata's somewhat shady former samurai past and a new pair of odd jobs collide, the action is bound to get so wild and demented that only a feature film will do it justice!  Sit down, strap yourself in, and make sure you're not wearing anything too tight or constricting as the junior half of OJG takes on the task of tracking down a tenacious terrorist while their silver-haired slickster of a partner seeks out a certain sword in the stunningly side-splitting and screwy Gin Tama!",
            "categoryid": 1,
        "productlength": 95,
            "mediumid": 1,
        "productcode": "GINTAMA",
        "productid": 1020,
            "publisherid": 66,
        "ratingid": 2,
        "producttitle": "Gin Tama: The Movie",
        "unitprice": 39.9797,
        "productyearcreated": 2012,
        "yourprice": 23.9898
    },
    {
        "productagerating": "PG-13",
        "productdescription": "China's highest grossing domestic film of all time!  According to ancient lore, if a human freely offers their heart to a demon, that monster can become mortal, experiencing the true pains and passions of existence. This is the ultimate triumph of the underworld. Xiaowei (Xun Zhou, THE GREAT MAGICIAN, FLYING SWORDS OF DRAGON GATE), a millennia-old fox spirit, is freed from her frozen prison and transforms into a dangerous seductress, consuming living hearts to keep her beautiful as she searches for her chance to become human. Meanwhile, Princess Jing (Wei Zhao, 14 BLADES, RED CLIFF, SHAOLIN SOCCER),hiding her marred beauty behind a golden mask, flees an unknown threat to her kingdom by pursuing the only man she ever loved: the guard who was unable to protect her, so many years ago. A twist of fate brings Princess Jing and Xiaowei together, and a slow game of wits, deceit, and seduction begins for the princess very own heart.",
            "categoryid": 9,
        "productlength": 132,
            "mediumid": 1,
        "productcode": "PAINTDSKIN",
        "productid": 1022,
            "publisherid": 65,
        "ratingid": 3,
        "producttitle": "Painted Skin: The Resurrection",
        "unitprice": 29.98,
        "productyearcreated": 2012,
        "yourprice": 9.99002
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Screen legend Chow Yun-fat stars as Confucius in the inspiring, action-packed saga of a leader whose wisdom and cunning were more powerful than any sword. In this sweeping battlefield epic, Confucius finds his lands threatened by the fires of war. After leading the nation’s most powerful army to victory against hordes of invaders, the new hero finds even greater danger in the jealous eyes of the aristocrats he fought to protect. From the Producer of John Woo’s Red Cliff and Jet Li’s Warlords, and captured on camera by Oscar-winning Director of Photography Peter Pau (Crouching tiger, Hidden Dragon), Chow Yun-fat delivers the award-nominated performance of a lifetime as a teacher, a military leader, and a legend in Confucius. ",
            "categoryid": 9,
        "productlength": 125,
            "mediumid": 6,
        "productcode": "CONFUCIUS",
        "productid": 1023,
            "publisherid": 18,
        "ratingid": 4,
        "producttitle": "CONFUCIUS",
        "unitprice": 24.98,
        "productyearcreated": 2012,
        "yourprice": 13.6401
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Frank Miller's groundbreaking Dark Knight Returns story arc is capably translated to a two-part, feature-length animated film, with the first installment serving as introduction to Miller's brooding, violent take on the venerable comic book hero. It is ten years after an aging Batman has retired, and Gotham City has sunk deeper into decadence and lawlessness. Now, when his city needs him most, the Dark Knight returns in a blaze of glory. Joined by Carrie Kelly, a teenage female Robin, Batman takes to the streets to end the threat of the mutant gangs that have overrun the city. And after facing off against his two greatest enemies, the Joker and Two-Face, for the final time, Batman finds himself in mortal combat with his former ally, Superman, in a battle that only one of them will survive. Actor Peter Weller (RoboCop) does a fine job as the aged Bruce Wayne, lured out of retirement to take on the Mutants, a vicious gang of criminals waging a terror campaign in Gotham City. Their brutal methods inspire the Batman to take an equally hard-nosed approach to crime fighting, which draws criticism from the powers that be and praise from the general public, especially 13-year-old Carrie Kelly (Ariel Winter of Modern Family), who becomes the new Robin. Director Jay Oliva and writer Bob Goodman ably condense the first two issues of the Dark Knight story arc into a 76-minute feature that preserves much of Miller's tone; the cast also provides the proper degree of vocal grit, with standout turns from Michael McKean, Gary Anthony Williams, and Michael Emerson in a brief but memorable bit as one of Batman's longest-running foes. Extras are limited to a preview of the second installment of The Dark Knight Returns, which when combined with the quality of the first part, should bring viewers back for the final go-round. ",
            "categoryid": 19,
        "productlength": 76,
            "mediumid": 1,
        "productcode": "DARKKNTR1",
        "productid": 1024,
            "publisherid": 63,
        "ratingid": 4,
        "producttitle": "Batman: The Dark Knight Returns - Part 1",
        "unitprice": 24.98,
        "productyearcreated": 2012,
        "yourprice": 17.9898
    },
    {
        "productagerating": "PG-13",
        "productdescription": "The epic adventure Thor spans the Marvel universe from present-day Earth to the cosmic realm of Asgard. At the center of the story is The Mighty Thor, a powerful but arrogant warrior whose reckless actions reignite an ancient war. As a result, Thor is banished to Earth where he is forced to live among humans. When the most dangerous villain of his world sends its darkest forces to invade Earth, Thor learns what it takes to be a true hero. ",
            "categoryid": 19,
        "productlength": 115,
            "mediumid": 1,
        "productcode": "THOR1",
        "productid": 1025,
            "publisherid": 36,
        "ratingid": 5,
        "producttitle": "THOR",
        "unitprice": 39.9902,
        "productyearcreated": 2011,
        "yourprice": 29.25
    },
    {
        "productagerating": "PG-13",
        "productdescription": "A mysterious event from Earth's past threatens to ignite a war so big that the Transformers alone will not be able to save the planet. Sam Witwicky (Shia LaBeouf) and the Autobots must fight against the darkness to defend our world from the Decepticons all-consuming evil in the smash hit from director Michael Bay and executive producer Steven Spielberg. ",
            "categoryid": 4,
        "productlength": 154,
            "mediumid": 1,
        "productcode": "TRANSFORM3",
        "productid": 1026,
            "publisherid": 36,
        "ratingid": 5,
        "producttitle": "Transformers: Dark of the Moon",
        "unitprice": 29.9898,
        "productyearcreated": 2011,
        "yourprice": 19.59
    },
    {
        "productagerating": "PG-13",
        "productdescription": "A good portion of Trekkies (or Trekkers, depending on one's level of Star Trek obsession) have special affection for episodes of the original TV series that related to Earth and other-Earth cultures visited by the crew of the Enterprise, version 1.0. Some of the shows unfolded in distorted forms of the past, some in the present day of Star Trek's future reality. Director J.J. Abrams recognized the importance of this relationship in his origin-story reboot of the franchise in 2009, and in Star Trek Into Darkness he has made it an even greater touchstone to the roots of Star Trek creator Gene Roddenberry's defining philosophy from nearly 50 years ago. The human home world is key to the plot of this spectacularly bold leap into Star Trek lore, which cleverly continues along the alternate path that was established as separate from the \"original\" Star Trek universe in Abrams's first whiz-bang crack at advancing the mythology. But it's not just Earth that is cool and imperiled in this rendering of adventure in the 23rd century; Into Darkness also plays with the original conceit that Earthlings were member to a multi-species United Federation of Planets ruled by a \"Prime Directive\" of noninterference with other civilizations. The conflict comes when rogue elements in the Earth-based Starfleet Command hunger to shift focus from peaceful exploration to militarization, a concept that is anathema to the crew of the Enterprise and her ongoing mission. The new cast is again inventively reunited, each of them further investing their characters with traits that reveal novel acting choices while staying true to the caricatures that are ingrained in our popular culture. The interplay between Chris Pine as Kirk and Zachary Quinto as Spock is deeper, and Zoe Saldana as Uhura is a solid third in their relationship. John Cho (Sulu), Simon Pegg (Scotty), Anton Yelchin (Chekov), and Karl Urban (McCoy) all have standout roles in the overall ensemble mystique as well as the plot-heavy machinations of this incarnation's narrative. Fortunately, the burdens of the story are well served by some important additions to the cast. Benedict Cumberbatch's Shakespearean aura, ferociously imperious gaze, and graceful athleticism make him a formidable villain as the mysterious Starfleet operative John Harrison. Harrison has initiated a campaign of terror on Earth before leading the Enterprise to even greater dangers in the enemy territory of Klingon-controlled space. That his background may make dedicated Trekkies/Trekkers gasp is just one acknowledgment of the substantial and ingrained legacy Star Trek has borne. There are many references, nods and winks to those with deep reverence for the folklore (some of them perhaps a little too close to being inside-baseball), though the fantastical and continually exciting story stands as an expertly crafted tale for complete neophytes. Another new face is Peter Weller--iconically famous in sci-fi-dom as RoboCop--here playing a steely, authoritative Starfleet bigwig who may also be following a hidden agenda. Not only is he running a covert operation, he's also at the helm of a fearsome secret starship that looms over the Enterprise like a shark poised to devour its prey. Which brings us to the awesome CGI effects driving the dazzling visual style of Into Darkness and the endlessly fascinating cosmos it makes real. The wow factor extends from the opening set piece on an alien world of primitive humanoids, garish vegetation, and a roiling volcano to the finale of destruction in a future San Francisco that is elegantly outfitted with gleaming-spired skyscrapers and all manner of flying vehicles. (London also gets a breathtaking 23rd-century makeover). Though Kirk and co. may bend it a little, the Prime Directive remains unbroken.",
            "categoryid": 4,
        "productlength": 132,
            "mediumid": 6,
        "productcode": "STARTREK2",
        "productid": 3136,
            "publisherid": 36,
        "ratingid": 5,
        "producttitle": "Star Trek: Into Darkness (Blu-Ray + DVD + Digital Copy)",
        "unitprice": 39.9902,
        "productyearcreated": 2013,
        "yourprice": 27.6901
    },
    {
        "productagerating": "PG-13",
        "productdescription": "A fellow named Bilbo Baggins lives in the Shire--but perhaps you've made his acquaintance already? If you're familiar with J.R.R. Tolkien's epic Lord of the Rings trilogy, and the films that Peter Jackson wrought from them, of course you have. And here is Bilbo, played again by Ian Holm, shuffling about his hobbit hole and recalling a grand adventure from his past, when he left the Shire with a wizard and some dwarves and found a certain ring and a very peculiar creature named Gollum. This is The Hobbit: An Unexpected Journey, which Jackson and his LOTR crew have expanded on from Tolkien's 1937 novel. And boy, have they expanded: this 169-minute escapade is merely the first of three separate movies made from that one book, and it gets the young Bilbo (played by Martin Freeman) only a little ways into his grand trek. Many loud, garish battles and chases fill the time, along with some (it pains one to say it) fairly tedious adolescent-level humor. Jackson tends to dally with scenes that might have been more effective in half the time, and the bumptious dwarves are some of the least charming characters in the Tolkieniad. Thank goodness, there's Gollum (played, as before, by the digitally transformed Andy Serkis), who shares a riddle-trading scene with Bilbo that sends genuine shivers up the spine. Ian McKellen returns as Gandalf, and a few other LOTR folk make cameos, but the more An Unexpected Journey goes on, the less you sense the magic afoot. Despite the fun moments, this feels like a prologue for the actual movie, which is still to come. (Originally released on many screens in 3-D, the film was also showcased in some theaters in a pioneering format that increased the clarity of the image--or made it look like a soap opera, depending on your receptiveness to the flat, frictionless technology.) ",
            "categoryid": 4,
        "productlength": 169,
            "mediumid": 3,
        "productcode": "LOTR4",
        "productid": 3155,
            "publisherid": 34,
        "ratingid": 4,
        "producttitle": "The Hobbit: An Unexpected Journey",
        "unitprice": 29.98,
        "productyearcreated": 2012,
        "yourprice": 16.9898
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Lord Voldemort has returned, but few want to believe it. In fact, the Ministry of Magic is doing everything it can to keep the wizarding world from knowing the truth - including appointing Ministry official Dolores Umbridge as the new Defense Against the Dark Arts teacher at Hogwarts. When Professor Umbridge refuses to train her students in practical defensive magic, a select group of students decides to learn on their own. With Harry Potter as their leader, these students (who call themselves \"\"Dumbledore's Army\"\") meet secretly in a hidden room at Hogwarts to hone their wizarding skills in preparation for battle with the Dark Lord and his Death Eaters. . New adventure - more dangerous , more thrilling than ever - is yours in this enthralling film version of the fifth novel in J.K. Rowling's Harry Potter series. A terrifying showdown between good and evil awaits. Prepare for battle! \n",
            "categoryid": 4,
        "productlength": 138,
            "mediumid": 3,
        "productcode": "POTTER5",
        "productid": 1138,
            "publisherid": 63,
        "ratingid": 4,
        "producttitle": "Harry Potter and the Order of the Phoenix\n",
        "unitprice": 14.9701,
        "productyearcreated": 2007,
        "yourprice": 10.99
    },
    {
        "productagerating": "PG-13",
        "productdescription": "For longtime viewers of the James Bond films, one of the larger pleasures of the series--aside from the eternally awesome jetpacks and ejector seats--has been watching it adapt itself to the times, scooting its unflappable central character past the Cold War to the Disco Age to beyond the Millennium seemingly without breaking a sweat. Skyfall, Daniel Craig's third turn in the tux, lands itself firmly in the utmost tier of the franchise, delivering the expected goods as well as a rather unusual vein of introspection. Celebrating the 50th year of Bond's existence, it continues cultivating the gritty, back-to-basics vibe of Casino Royale, while also slowly letting some of the more fancifully escapist elements in through the filters. Kicking off with a humdinger of a car/bike/train chase in Istanbul, the plot finds an aging 007 on uneasy footing, struggling to get back in the game while his boss M (a magnificent Judi Dench) is marked for death by a mysterious assassin. As Bond draws closer to his target (Javier Bardem, having an absolute blast), he uncovers some details that draw uncomfortably close to his own origins. Director Sam Mendes, an Oscar winner for American Beauty, ably brings his game to the blockbuster level, keeping the globe-hopping narrative moving at a swift pace while also allowing plenty of room for the cast (including newcomers Ralph Fiennes and Naomie Harris) to do their thing. For all of the talent assembled on both sides of the camera, however, Skyfall's true MVP proves to be director of photography Roger Deakins, who gives an astonishingly ravishing look to the proceedings, culminating in a battle in a Shanghai skyscraper that may very well be the best fight scene the series has ever had. By the time of the surprisingly moving finale, set in a location far, far away from the standard Evil Lair, Mendes and Craig and Co. have reminded the viewer of exactly what these films can do. Where it ends is a perfect beginning. Extras on the disc include a wry and informative director's track, a more laid-back commentary from the producers and production designer, and an exhaustively detailed look behind the scenes. If you want to learn more about Bardem's wig, that information is available.",
            "categoryid": 4,
        "productlength": 138,
            "mediumid": 3,
        "productcode": "007SKYFALL",
        "productid": 3154,
            "publisherid": 31,
        "ratingid": 5,
        "producttitle": "SKYFALL",
        "unitprice": 29.98,
        "productyearcreated": 2012,
        "yourprice": 14.7799
    },
    {
        "productagerating": "13+",
        "productdescription": "Ten days before Christmas, it seemed like just another ordinary day for the SOS Brigade; Haruhi came up with another one of her crazy ideas to hold a Christmas party in the club room. But things got weirder from there... The next day Kyon woke up to a world in which Haruhi didn't exist and no one besides him had any memory of her. How can someone like Haruhi Suzumiya, who's supposed to be center of the universe, just vanish?",
            "categoryid": 6,
        "productlength": 164,
            "mediumid": 3,
        "productcode": "HARUHIDIS",
        "productid": 1027,
            "publisherid": 7,
        "ratingid": 5,
        "producttitle": "The Melancholy of Haruhi Suzumiya Movie: The Disappearance of Haruhi",
        "unitprice": 29.98,
        "productyearcreated": 2011,
        "yourprice": 22.4898
    },
    {
        "productagerating": "13+",
        "productdescription": "The stage for a final showdown is prepared as Anna Williams and the G Corporation set a trap for her sister Nina, who works for Jin Kazama, head of the Mishima Zaibatsu. Both Jin and his father, Kazuya Mishima of the G Corporation, seek to possess and control the M Cell that will unlock the destructive supernatural powers buried within the Mishima bloodline.\nKazuya dispatches Ling Xiaoyu to a prestigious international school to spy on Shin Kamiya, a victim of secret genetic experiments and may hold the key to the M Cell. While investigating Shin, Xiaoyu befriends Alisa Bosconovitch who also shows an interest in Shin. Their new friendship is put to the test as they are caught in the middle of the Mishima family feud.\nThe final battle explodes in a three way battle. Who will claim the M Cell and unlock the full power of the Devil Gene?!",
            "categoryid": 1,
        "productlength": 92,
            "mediumid": 3,
        "productcode": "TEKKENVENG",
        "productid": 1028,
            "publisherid": 7,
        "ratingid": 4,
        "producttitle": "Tekken: Blood Vengeance",
        "unitprice": 19.98,
        "productyearcreated": 2011,
        "yourprice": 14.99
    },
    {
        "productagerating": "PG-13",
        "productdescription": "Actor-turned-director Stephen Fung's Tai Chi Zero is a frenetic, genre-bending martial arts fantasy that tips its hat to Chinese action cinema of the past while taking a radical approach to its future via a torrent of references to video games, animation, American movies, and other pop culture ephemera. Olympic wushu champion Yuan Xiaochao is top-billed as Lu Chan, an impulsive kung fu prodigy who's loosely (make that very loosely) based on real-life tai chi teacher Yang Luchan. The movie's Lu Chan also sports a horn on his skull that, when pressed, substantially boosts his powers but also drains his energy (shown on-screen as a diminishing, Xbox-like icon). To control his talents and save his life, Lu Chan travels to the Chen village, where the inhabitants have mastered the art of tai chi. There, he is faced with not only the locals' reluctance to share their secrets, but a former resident (Eddie Peng) who threatens to bulldoze the village with a monstrous, steampunk-influenced machine to make way for the railroad and the 20th century. Lu Chan's fight to save the town is depicted in a meta-flurry of information à la Edgar Wright's Scott Pilgrim vs. the World: actors and their characters, as well as various fighting styles, are introduced by pop-up-styled titles, while the combat itself unfolds via rapid-eye editing and camera angles. Stylistic references to silent film, European westerns, and anime are also woven liberally throughout the picture, but the manic pace and deluge of visual information obscures not only the martial arts choreography by Hong Kong legend Sammo Hung, but also more affectionate touches like cameos by kung fu veterans Bruce Leung and Xiong Xin-Xin and Infernal Affairs director Andrew Lau. Tai Chi Zero's attention deficit disorder aesthetic even extends to its basic structure, with the picture ending abruptly, rewinding, and then previewing Fung's 3-D follow-up, Tai Chi Hero. Longtime Asian-action fans may find this much media overload ado over nothing, though the film's extraordinary popularity abroad indicates that its approach has found favor with newer audiences. ",
            "categoryid": 12,
        "productlength": 95,
            "mediumid": 3,
        "productcode": "TAICHI0",
        "productid": 3162,
            "publisherid": 65,
        "ratingid": 3,
        "producttitle": "Tai Chi Zero",
        "unitprice": 24.98,
        "productyearcreated": 2013,
        "yourprice": 11.5399
    }
]
